#!/bin/bash
# vim: set ts=4 sts=4 sw=4 et:

DOMAIN_ADMIN="${DOMAIN_ADMIN:-Administrator}"
DOMAIN_PASSWORD="${DOMAIN_PASSWORD:-P@ssw0rd}"
SERVER_KEY_FILE="${SERVER_KEY_FILE:-/etc/ssl/private/ssl-cert-snakeoil.key}"
SERVER_CERT_FILE="${SERVER_CERT_FILE:-/etc/ssl/certs/ssl-cert-snakeoil.pem}"
SERVER_CA_FILE="${SERVER_CA_FILE:-/etc/ssl/certs/ca-certificates.crt}"
SERVER_KEY_FILE_DEST="/etc/freeradius/3.0/certs/server.key"
SERVER_CERT_FILE_DEST="/etc/freeradius/3.0/certs/server.crt"
SERVER_CA_FILE_DEST="/etc/freeradius/3.0/certs/ca.crt"

if [ -f /configure ]; then
    /configure
    rm /configure
fi

# Join domain
net join -U ${DOMAIN_ADMIN}%${DOMAIN_PASSWORD} 

# Start domain services
service smbd start
service winbind start

# Config FreeRADIUS to use certs
cp ${SERVER_KEY_FILE} ${SERVER_KEY_FILE_DEST}
cp ${SERVER_CERT_FILE} ${SERVER_CERT_FILE_DEST}
cp ${SERVER_CA_FILE} ${SERVER_CA_FILE_DEST}
chown freerad:freerad ${SERVER_KEY_FILE_DEST}
chown freerad:freerad ${SERVER_CERT_FILE_DEST}
chown freerad:freerad ${SERVER_CA_FILE_DEST}
chmod +r ${SERVER_KEY_FILE_DEST}
chmod +r ${SERVER_CERT_FILE_DEST}
chmod +r ${SERVER_CA_FILE_DEST}

# Configure RADIUS client, /etc/freeradius/clients.conf

exec "$@"