#!/bin/bash
# vim: set ts=4 sts=4 sw=4 et:

DOMAIN_ADMIN="${DOMAIN_ADMIN}"
DOMAIN_PASSWORD="${DOMAIN_PASSWORD}"

SERVER_KEY_FILE_DEST="${SERVER_KEY_FILE_DEST}"
SERVER_CERT_FILE_DEST="${SERVER_CERT_FILE_DEST}"
SERVER_CA_FILE_DEST="${SERVER_CA_FILE_DEST}"

if [ -f /configure ]; then
    /configure
    rm /configure
fi

# Join domain
net join -U ${DOMAIN_ADMIN}%${DOMAIN_PASSWORD} 

# Start domain services
service smbd start
service winbind start

# Config FreeRADIUS to use certs
chown freerad:freerad ${SERVER_KEY_FILE_DEST}
chown freerad:freerad ${SERVER_CERT_FILE_DEST}
chown freerad:freerad ${SERVER_CA_FILE_DEST}
chmod +r ${SERVER_KEY_FILE_DEST}
chmod +r ${SERVER_CERT_FILE_DEST}
chmod +r ${SERVER_CA_FILE_DEST}

# Configure RADIUS client, /etc/freeradius/clients.conf

exec "$@"